# membuat data list
list_buah = ['pir', 'mangga', 'lemon', 'zaki indomie']
print("list nama buah", list_buah)
print(list_buah[0])
print(list_buah[1])
print(list_buah[2])
print(list_buah[3])

print(list_buah[0:1])
print(list_buah[0:2])
print(list_buah[1:3])
print(list_buah[0:-1])
print(list_buah[-1:-3])
print(list_buah[-1:3])
print(list_buah[-3:-1])

print(list_buah[0:])
print(list_buah[1:])
print(list_buah[2:])
print(list_buah[3:])
print(list_buah[:0])
print(list_buah[:1])
print(list_buah[:2])
print(list_buah[:3])
print(list_buah[:4])